[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=77.0.3" ]

[project]
name = "dbreport"
description = "Generate html reports of views in a sqlite3 database"
readme = "README.md"
keywords = [ "html", "report", "sqlite", "sqlite3" ]
license = { text = "MIT" }
authors = [ { name = "Joseph Contreras", email = "26684136+JosephJContreras@users.noreply.github.com" } ]
requires-python = ">=3.8"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]
dependencies = [ "beautifulsoup4", "jinja2" ]
optional-dependencies.dev = [
  "beautifulsoup4",
  "black",
  "build",
  "flake8",
  "isort",
  "pre-commit",
  "pylint",
  "pyproject-fmt",
  "pytest",
  "pytest-cov",
  "sphinx",
  "text-unidecode",
  "validate-pyproject[all]",
]
urls.Homepage = "https://dbreport.readthedocs.io/en/latest/index.html"

[tool.setuptools]
dynamic.version = { attr = "dbreport.__version__" }
package-data.dbreport = [
  "templates/*.j2",
  "templates/*.json",
  "templates/static/css/*.css",
]
package-data."*" = [ "License.txt" ]
packages.find.where = [ "." ]

[tool.black]
line-length = 88

[tool.isort]
force_alphabetical_sort_within_sections = true
group_by_package = true
lines_between_sections = 1
lines_between_types = 1
multi_line_output = 3
profile = "black"

[tool.pytest]
ini_options.filterwarnings = []
